nama = input("Nama: ")
NIM = input("NIM: ")
Paralel = input("Kelas Paralel: ")
Lahir = input("Tempat/Tanggal Lahir: ")
Alamat = input("Alamat: ")
Hobi = input("Hobi: ")
No_HP = input("No HP: ")

print("Nama                 : " + nama)
print("NIM                  : " + NIM)
print("Kelas Paralel        : " + Paralel)
print("Tempat/Tanggal Lahir : " + Lahir)
print("Alamat               : " + Alamat)
print("Hobi                 : " + Hobi)
print("No HP                : " + No_HP)